image: registry.gitlab.com/snopek-games/godot-builder-docker:latest

stages:
  - build

build:
  image: registry.gitlab.com/snopek-games/godot-builder-docker:latest
  stage: build
  tags:
    - multicore
  variables:
    GODOT_DOWNLOAD_URL: "https://github.com/godotengine/godot/archive/3.3.4-stable.tar.gz"
  parallel:
    matrix:
      - BUILD_TYPE:
        - linux-editor-64
        - linux-export-template-debug-64
        - linux-export-template-release-64
        - windows-editor-64
        - windows-export-template-debug-64
        - windows-export-template-release-64
        - macosx-editor-64
        - macosx-export-template-debug-64
        - macosx-export-template-release-64
        - html5-export-template-debug
        - html5-export-template-release
  script:
    - podman login "$GODOT_BUILD_REGISTRY" $PODMAN_OPTS --username="$GODOT_BUILD_REGISTRY_USERNAME" --password="$GODOT_BUILD_REGISTRY_PASSWORD"
    - ./scripts/build-godot.sh
  #rules:
  #  - if: '$CI_COMMIT_MESSAGE =~ /\[build godot\]/'
  #  - changes:
  #    - godot/**/*
  artifacts:
    name: sg-physics-2d-$BUILD_TYPE
    paths:
      - build/godot/bin

