#!/usr/bin/env python

Import("env")
Import("env_modules")

env_sg_physics_2d = env_modules.Clone()

sg_physics_2d_subdirs = [
    "",
    "internal/",
    "math/",
    "servers/",
    "scene/2d/",
    "scene/resources/",
    "editor/",
]

# Add the sources for libfixmath
env_sg_physics_2d.Append(CPPDEFINES = [
    'FIXMATH_NO_OVERFLOW',
    'FIXMATH_NO_ROUNDING',
])
env_sg_physics_2d.add_source_files(env.modules_sources, "thirdparty/libfixmath/*.c")

for d in sg_physics_2d_subdirs:
    env_sg_physics_2d.add_source_files(env.modules_sources, d + "*.cpp")

